"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ as dj_environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = dj_environ.Env()
env.read_env(str(BASE_DIR / ".env")) 

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "post_login" 
LOGOUT_REDIRECT_URL = 'product_list'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER 
SITE_NAME = env("SITE_NAME", default="eCommerce")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default='django-insecure-m7^#^=8+ix_szs0**h0+bk8gy-x#!x5egjr1n_ykj$^laabzcw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
AUTH_URL = "https://x.com/i/oauth2/authorize" 
TOKEN_URL = "https://api.x.com/2/oauth2/token"
TWEET_URL = "https://api.x.com/2/tweets"
MEDIA_UPLOAD_URL = "https://api.x.com/2/media/upload"
MEDIA_STATUS_URL = "https://api.x.com/2/media/upload?command=STATUS&media_id={id}"
MEDIA_INIT_URL = "https://api.x.com/2/media/upload/initialize"
MEDIA_APPEND_URL_TMPL = "https://api.x.com/2/media/upload/{media_id}/append"
MEDIA_FINALIZE_URL_TMPL = "https://api.x.com/2/media/upload/{media_id}/finalize"


ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "0.0.0.0"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "shop.apps.ShopConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


#Maria DB / MySQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DATABASE_NAME", default="myproject_db"),
        "USER": env("DATABASE_USER", default="myproject_user"),
        "PASSWORD": env("DATABASE_PASSWORD", default="StrongAppPW123!"),
        "HOST": env("DATABASE_HOST", default="db"),
        "PORT": env("DATABASE_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    }
}
#SQL Lite
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""

TWITTER_ENABLED = env.bool("TWITTER_ENABLED", default=False)
TWITTER_AUTH_MODE = env("TWITTER_AUTH_MODE", default="oauth2")
TWITTER_CLIENT_ID = env("TW_CLIENT_ID", default=None)
TWITTER_CLIENT_SECRET = env("TW_CLIENT_SECRET", default=None)
TWITTER_REDIRECT_URI = env("TW_REDIRECT_URI", default="http://127.0.0.1:8000/twitter/callback")
TWITTER_SCOPES = ["tweet.read", "tweet.write", "users.read", "offline.access","media.write"]
TWITTER_TOKEN_PATH = str(BASE_DIR / ".twitter_tokens.json")

"""
TWITTER = {
    "TWITTER_CLIENT_ID": os.getenv("TW_CONSUMER_KEY"),
    "ACCESS_TOKEN": os.getenv("TWITTER_ACCESS_TOKEN"),
    "ACCESS_TOKEN_SECRET": os.getenv("TWITTER_ACCESS_TOKEN_SECRET"),
}
"""

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

PASSWORD_RESET_TOKEN_TTL_MINUTES = 15
SITE_NAME = "eCommerce"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASKET_SESSION_ID = "basket"